version: '3.8'

# Services
services:
    # PHP Service
    php:
        build:
            dockerfile: php-dockerfile
            context: .
            target: development
        volumes:
            - './www:/var/www/html'
            - './new_user_email.html:/new_user_email.html:ro'
            - 'images:/images'
            - './config/php/php.ini-development:/usr/local/etc/php/php.ini:ro'
        depends_on:
            - mysql
        environment:
            BB_CONFIG_FILE: /run/secrets/bb_config
            DB_PASSWORD_FILE: /run/secrets/db_root_password
        secrets:
            - bb_config
            - db_root_password

    # Nginx Service
    nginx:
        image: nginx:latest
        ports:
            - 30000:80
        volumes:
            - './www:/var/www/html'
            - './config/nginx:/etc/nginx/conf.d:ro'
        depends_on:
            - php

    # MySQL Service
    mysql:
        image: mysql:8.3
        environment:
            MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db_root_password
        ports:
            - 30001:3306
        volumes:
            - mysqldata:/var/lib/mysql
        secrets:
            - db_root_password

# Secrets
secrets:
    db_root_password:
        file: db_root_password.txt
    bb_config:
        file: bb_config.ini

# Volumes
volumes:
    mysqldata:
    images:
