version: '3.8'

# Services
services:
    # PHP Service
    php:
        build:
            dockerfile: php-dockerfile
        volumes:
            - './www:/var/www/html'
            - './config/php:/usr/local/etc/php'
            - 'images:/images'
        depends_on:
            - mysql
        environment:
            DB_HOSTNAME: 'mysql'
            DB_PORT: '3306'
            DB_USERNAME: 'root'
            DB_PASSWORD_FILE: /run/secrets/db_root_password
            DB_NAME: 'betterbuys'
        secrets:
            - db_root_password

    # Nginx Service
    nginx:
        image: nginx:latest
        ports:
            - 30000:80
        volumes:
            - './www:/var/www/html'
            - './nginx-conf:/etc/nginx/conf.d'
            - 'images:/var/www/html/images'
        depends_on:
            - php

    # MySQL Service
    mysql:
        image: mysql:8.3
        environment:
            MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db_root_password
        ports:
            - 30001:3306
        volumes:
            - mysqldata:/var/lib/mysql
        secrets:
            - db_root_password

# Secrets
secrets:
    db_root_password:
        file: db_root_password.txt

# Volumes
volumes:
    mysqldata:
    images:
